version: '2.3'
services:
  cvat_elasticsearch:
    container_name: cvat_elasticsearch
    image: cvat_elasticsearch
    networks:
      default:
        aliases:
          - elasticsearch
    build:
      context: ./analytics/elasticsearch
      args:
        ELK_VERSION: 6.4.0
    restart: always

  cvat_kibana:
    container_name: cvat_kibana
    image: cvat_kibana
    networks:
      default:
        aliases:
          - kibana
    build:
      context: ./analytics/kibana
      args:
        ELK_VERSION: 6.4.0
    ports:
      - "5601:5601"
    restart: always

  cvat_logstash:
    container_name: cvat_logstash
    image: cvat_logstash
    networks:
      default:
        aliases:
          - logstash
    build:
      context: ./analytics/logstash
      args:
        ELK_VERSION: 6.4.0
        http_proxy:  ${http_proxy}
        https_proxy: ${https_proxy}
    restart: always

  cvat:
    environment:
      DJANGO_LOG_SERVER_URL: "http://logstash:5000"
      no_proxy: logstash,${no_proxy}
