version: '2.3'
services:
  cvat_elasticsearch:
    container_name: cvat_elasticsearch
    image: cvat_elasticsearch
    networks:
      default:
        aliases:
          - elasticsearch
    build:
      context: ./analytics/elasticsearch
      args:
        ELK_VERSION: 6.4.0
    restart: always

  cvat_kibana:
    container_name: cvat_kibana
    image: cvat_kibana
    networks:
      default:
        aliases:
          - kibana
    build:
      context: ./analytics/kibana
      args:
        ELK_VERSION: 6.4.0
    ports:
      - "5601:5601"
    depends_on: ['cvat_elasticsearch']
    restart: always

  cvat_kibana_setup:
    image: centos:7
    container_name: cvat_kibana_setup
    volumes: ['./analystics/kibana/setup.sh:/usr/local/bin/kibana-setup.sh:ro']
    depends_on: ['cvat_kibana']
    command: ['/bin/bash', '-c', '/usr/local/bin/kibana-setup.sh']

  cvat_logstash:
    container_name: cvat_logstash
    image: cvat_logstash
    networks:
      default:
        aliases:
          - logstash
    build:
      context: ./analytics/logstash
      args:
        ELK_VERSION: 6.4.0
        http_proxy:  ${http_proxy}
        https_proxy: ${https_proxy}
    depends_on: ['cvat_elasticsearch']
    restart: always

  cvat:
    environment:
      DJANGO_LOG_SERVER_URL: "http://logstash:5000"
      no_proxy: logstash,${no_proxy}
