{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: cvat-postgres-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: cvat-app
    tier: db
spec:
  type: ClusterIP
  selector:
      app: cvat-app
      tier: db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: http
{{- end }}
