{{- if .Values.database.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvat-postgres-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
{{- end }}
