{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cvat.labels" . | nindent 4 }}
    app: cvat-app
    tier: backend
spec:
  type: ClusterIP
  selector:
      {{- include "cvat.labels" . | nindent 6 }}
      app: cvat-app
      tier: backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
{{- end }}
