comment:
  layout: "header, diff, flags, components"

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto

  individual_components:
    - component_id: cvat-ui
      name: cvat-ui
      paths:
        - cvat-canvas/**
        - cvat-core/**
        - cvat-data/**
        - cvat-ui/**
    - component_id: cvat-server
      name: cvat-server
      paths:
        - cvat/**
        - cvat-cli/**
        - cvat-sdk/**
        - utils/**

