#
# Copyright (C) 2018 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
version: "2.3"

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10.3-alpine
    networks:
      default:
        aliases:
          - db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
    volumes:
      - cvat_db:/var/lib/postgresql/data

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0.5-alpine
    networks:
      default:
        aliases:
          - redis
    restart: always

  cvat_setup:
    container_name: cvat_setup
    image: busybox
    volumes:
      - ./cvat/apps/engine:/cvat:ro
      - cvat_anno_dumpers:/anno_dumpers:rw
      - cvat_anno_parsers:/anno_parsers:rw
    entrypoint: [
      'sh',
      '-c',
      'cp -r /cvat/anno_dumpers/. /anno_dumpers && chown -R 1000:1000 /anno_dumpers && cp -r /cvat/anno_parsers/. /anno_parsers && chown -R 1000:1000 /anno_parsers']

  cvat:
    container_name: cvat
    image: cvat
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
      - cvat_setup
    ports:
      - "8080:8080"
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
        TF_ANNOTATION: "no"
        USER: "django"
        DJANGO_CONFIGURATION: "production"
        WITH_TESTS: "no"
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ""
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - cvat_models:/home/django/models
      - cvat_anno_dumpers:/home/django/anno_dumpers
      - cvat_anno_parsers:/home/django/anno_parsers

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_models:
  cvat_anno_dumpers:
  cvat_anno_parsers:
