#
# Copyright (C) 2018-2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
version: "2.3"

services:
  cvatdb:
    container_name: cvatdb
    image: postgres:10-alpine
    networks:
      default:
        aliases:
          - db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    deploy:
      resources:
        limits:
          cpus: '0.25'

  cvat-redis:
    container_name: cvat-redis
    image: redis:4.0-alpine
    networks:
      default:
        aliases:
          - redis
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'

  cvat:
    container_name: cvat
    image: labeling.azurecr.io/cvat/server
    restart: always
    depends_on:
      - cvat-redis
      - cvatdb
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy: nuclio,${no_proxy}
        socks_proxy:
        USER: "django"
        DJANGO_CONFIGURATION: "production"
        TZ: "Etc/UTC"
        CLAM_AV: "no"
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ""
      ALLOWED_HOSTS: '*'
      CVAT_REDIS_HOST: "cvat-redis"
      CVAT_POSTGRES_HOST: "cvatdb"
    volumes:
      - cvatdata:/home/django/data
      - cvatkeys:/home/django/keys
      - cvatlogs:/home/django/logs
      - cvatmodels:/home/django/models
    deploy:
      resources:
        limits:
          cpus: '0.25'

  cvat-ui:
    container_name: cvat-ui
    image: labeling.azurecr.io/cvat/ui
    restart: always
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
      dockerfile: Dockerfile.ui
    networks:
      default:
        aliases:
          - ui
    depends_on:
      - cvat
    deploy:
      resources:
        limits:
          cpus: '0.25'


  cvat-proxy:
    container_name: cvat-proxy
    image: labeling.azurecr.io/cvat/proxy
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.proxy
    depends_on:
      - cvat
      - cvat-ui
    environment:
      CVAT_HOST: localhost
    command: /bin/sh -c "envsubst '$$CVAT_HOST' < /etc/nginx/conf.d/cvat.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: '0.25'


networks:
  default:
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

volumes:
  cvatdbstorage:
    driver: azure_file
    driver_opts:
      share_name: cvatdbstorage
      storage_account_name: saveinstorage
  cvatdata:
    driver: azure_file
    driver_opts:
      share_name: cvatdata
      storage_account_name: saveinstorage
  cvatkeys:
    driver: azure_file
    driver_opts:
      share_name: cvatkeys
      storage_account_name: saveinstorage
  cvatlogs:
    driver: azure_file
    driver_opts:
      share_name: cvatlogs
      storage_account_name: saveinstorage
  cvatmodels:
    driver: azure_file
    driver_opts:
      share_name: cvatmodels
      storage_account_name: saveinstorage
  cvatnginxconfig:
    driver: azure_file
    driver_opts:
      share_name: cvatnginxconfig
      storage_account_name: saveinstorage


