# Default values for cvat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

cvat:
    backend:
        replicas: 1
        image: openvino/cvat_server
        tag: latest
        labels: {}
        #  test: test
        annotations: {}
        # test.io/test: test
        resources: {}
        affinity: {}
        # nodeAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #     nodeSelectorTerms:
        #     - matchExpressions:
        #       - key: kubernetes.io/e2e-az-name
        #         operator: In
        #         values:
        #         - e2e-az1
        #         - e2e-az2
        additionalEnv: []
        # Example:
        #  - name: volume-from-secret
        # - name: TEST
        #  value: "test"
        additionalVolumes: []
        # Example(assumes that pvc was already created):
        # - name: tmp
        #   persistentVolumeClaim:
        #       claimName: tmp
        additionalVolumeMounts: []
        # Example:
        # -   mountPath: /tmp
        #     name: tmp
        #     subPath: test
        service: {}
    frontend:
        replicas: 1
        image: openvino/cvat_ui
        tag: latest
        labels: {}
        #  test: test
        annotations: {}
        # test.io/test: test
        resources: {}
        affinity: {}
        # nodeAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #     nodeSelectorTerms:
        #     - matchExpressions:
        #       - key: kubernetes.io/e2e-az-name
        #         operator: In
        #         values:
        #         - e2e-az1
        #         - e2e-az2
        additionalEnv: []
        # Example:
        #  - name: volume-from-secret
        # - name: TEST
        #  value: "test"
        additionalVolumes: []
        # Example(assumes that pvc was already created):
        # - name: tmp
        #   persistentVolumeClaim:
        #       claimName: tmp
        additionalVolumeMounts: []
        # Example:
        # -   mountPath: /tmp
        #     name: tmp
        #     subPath: test
        service: {}

postgresql:
    #See https://github.com/bitnami/charts/blob/master/bitnami/postgresql/ for more info
    enabled: true # false for external db
    external:
        host: 127.0.0.1
        port: 5432
        user: postgres
        password: postgres
        dbname: cvat

    # If not external follwoing config will apply by default
    global:
        postgresql:
            existingSecret: cvt-test-postgres-secret
    secret:
        create: true
        name: postgres-secret
        password: cvat_postgresql
        postgres_password: cvat_postgresql_postgres
        replication_password: cvat_postgresql_replica
    postgresqlDatabase: cvat
    postgresqlUsername: cvat
    service:
        port: 5432

redis:
    #See https://github.com/bitnami/charts/blob/master/bitnami/redis/ for more info
    enabled: true
    usePassword: false
    cluster:
        enabled: false

ingress:
    enabled: false
#    annotations:
#        kubernetes.io/ingress.class: nginx
#        # cert-manager.io/cluster-issuer:"your-issuer-name"
#        ingress.kubernetes.io/ssl-redirect: "true"
#    hosts:
#        - host: cvat.example.com
#          paths:
#            - match: "/api/.*|git/.*|tensorflow/.*|auto_annotation/.*|analytics/.*|static/.*|admin|admin/.*|documentation/.*|dextr/.*|reid/.*"
#              service:
#                  name: cvat-backend-service
#                  port: 8080
#            - match : "/"
#              service:
#                  name: cvat-frontend-service
#                  port: 80
#    tls:
#        - hosts:
#              - cvat.example.com
#          secretName: ingress-tls-cvat
