{{- if .Values.analytics.enabled }}
apiVersion: v1
kind: Secret
metadata:
  # vector helm doesn't allow template name of CM
  name: cvat-clickhouse-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cvat.labels" . | nindent 4 }}
    app: cvat-app
    tier: clickhouse
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion }}
immutable: true
{{- end }}
stringData:
{{ (.Files.Glob "analytics/clickhouse/*.sh").AsSecrets | indent 2 }}
{{- end}}
