{{- $localValues := .Values.cvat.backend.initializer -}}

apiVersion: batch/v1
kind: Job
metadata:
  # Jobs are mostly immutable, so Helm can't update them when the user upgrades
  # a release. Work around this by including the revision in the job name, so that
  # every upgrade creates a new job.
  # See also <https://github.com/helm/helm/issues/7082>.
  name: {{ .Release.Name }}-backend-initializer-r{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: cvat-app
    tier: backend
    component: initializer
    {{- include "cvat.labels" . | nindent 4 }}
    {{- with $localValues.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $localValues.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      labels:
        app: cvat-app
        tier: backend
        component: initializer
        {{- include "cvat.labels" . | nindent 8 }}
        {{- with $localValues.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $localValues.annotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: cvat-backend
          image: {{ .Values.cvat.backend.image }}:{{ .Values.cvat.backend.tag }}
          imagePullPolicy: {{ .Values.cvat.backend.imagePullPolicy }}
          {{- with $localValues.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          args: ["init"]
          env:
          {{ include "cvat.sharedBackendEnv" . | indent 10 }}
          {{- with $localValues.additionalEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with $localValues.additionalVolumeMounts }}
          volumeMounts:
          {{- toYaml . | nindent 10 }}
          {{- end }}
      restartPolicy: OnFailure
      {{- with $localValues.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $localValues.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $localValues.additionalVolumes }}
      volumes:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
