version: '3.8'

services:
  cvat_server:
    image: cvat/server:dev
    build:
      dockerfile: .devcontainer/Dockerfile
      context: .
      args:
        - pull
        - CONTAINER_USER=${CONTAINER_USER}
        - HOST_USER_UID=${HOST_USER_UID}
    restart: no
    entrypoint: ["/bin/bash", "-c"]
    command: ["sleep infinity"]
    environment:
      IAM_OPA_HOST: http://opa:8181
      DJANGO_LOG_SERVER_HOST: ${DJANGO_LOG_SERVER_HOST}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
    volumes:
      - cvat_data:/home/${CONTAINER_USER}/workspace}/data:rw
      - cvat_keys:/home/${CONTAINER_USER}/workspace}/keys:rw
      - cvat_logs:/home/${CONTAINER_USER}/workspace}/logs:rw

  cvat_db:
    restart: no

  cvat_redis_inmem:
    restart: no

  cvat_redis_ondisk:
    restart: no

  cvat_opa:
    restart: no


volumes:
  cvat_db:
    name: cvat_db_${GIT_BRANCH}
  cvat_data:
    name: cvat_data_${GIT_BRANCH}
  cvat_keys:
    name: cvat_keys_${GIT_BRANCH}
  cvat_logs:
    name: cvat_logs_${GIT_BRANCH}
  cvat_inmem_db:
    name: cvat_inmem_db_${GIT_BRANCH}
  cvat_cache_db:
    name: cvat_cache_db_${GIT_BRANCH}



