version: '3.8'

name: devcontainer

services:
  cvat_server:
    image: cvat/server:devcontainer
    build:
      dockerfile: .devcontainer/Dockerfile
      context: .
      args:
        - pull # To fetch upstream base image (cvat/server:dev) changes on container rebuild
        - HOST_USER_UID=${HOST_USER_UID}
    restart: no
    entrypoint: ["/bin/bash", "-c"]
    command: ["sleep infinity"]
    environment:
      IAM_OPA_HOST: http://opa:8181
      DJANGO_LOG_SERVER_HOST: ${DJANGO_LOG_SERVER_HOST}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
    volumes:
      - cvat_data:/home/devcontainer/workspace/data
      - cvat_keys:/home/devcontainer/workspace/keys
      - cvat_logs:/home/devcontainer/workspace/logs
      # For improving write performance on non-linux machines
      - cvat_node_modules:/home/devcontainer/workspace/node_modules

  cvat_db:
    restart: no

  cvat_redis_inmem:
    restart: no

  cvat_redis_ondisk:
    restart: no

  cvat_opa:
    restart: no

# VS code shuts down containers upon closing the window. If in any case if it to shut down the containers
# they should not restart upon system restart. This shall save unncessary memory usage of the system when not
# developing

volumes:
  cvat_node_modules:
  cvat_db:
    name: cvat_db_${GIT_BRANCH}
  cvat_data:
    name: cvat_data_${GIT_BRANCH}
  cvat_keys:
    name: cvat_keys_${GIT_BRANCH}
  cvat_logs:
    name: cvat_logs_${GIT_BRANCH}
  cvat_inmem_db:
    name: cvat_inmem_db_${GIT_BRANCH}
  cvat_cache_db:
    name: cvat_cache_db_${GIT_BRANCH}

# Volumes are parameterized with the current git branch values to isolate development environment based on git branches

