{{- $version := .Capabilities.KubeVersion.GitVersion -}}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "cvat.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cvat.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- if .Values.ingress.hostname }}
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      {{- range tuple "api" "admin" "static" "django-rq" "profiler" }}
      - path: {{ print "/" . }}
        {{- if $.Values.ingress.pathType }}
        pathType: {{ $.Values.ingress.pathType }}
        {{- end }}
        backend:
          service:
            name: {{ $.Release.Name }}-backend-service
            port:
              number: 8080
      {{- end }}
      - path: /
        {{- if .Values.ingress.pathType }}
        pathType: {{ .Values.ingress.pathType }}
        {{- end }}
        backend:
          service:
            name: {{ .Release.Name }}-frontend-service
            port:
              number: 80
  {{- end }}
{{- end }}
