{{- $localValues := .Values.cvat.backend.worker.webhooks -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-worker-webhooks
  namespace: {{ .Release.Namespace }}
  labels:
    app: cvat-app
    tier: backend
    component: worker-webhooks
    {{- include "cvat.labels" . | nindent 4 }}
    {{- with $localValues.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $localValues.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $localValues.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "cvat.labels" . | nindent 6 }}
      {{- with $localValues.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      app: cvat-app
      tier: backend
      component: worker-webhooks
  template:
    metadata:
      labels:
        app: cvat-app
        tier: backend
        component: worker-webhooks
        {{- include "cvat.labels" . | nindent 8 }}
        {{- with $localValues.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $localValues.annotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: cvat-backend
          image: {{ .Values.cvat.backend.image }}:{{ .Values.cvat.backend.tag }}
          imagePullPolicy: {{ .Values.cvat.backend.imagePullPolicy }}
          {{- with $localValues.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          args: ["run", "worker.webhooks"]
          env:
          {{ include "cvat.sharedBackendEnv" . | indent 10 }}
          {{- with $localValues.additionalEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with $localValues.additionalVolumeMounts }}
          volumeMounts:
          {{- toYaml . | nindent 10 }}
          {{- end }}
      {{- with $localValues.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $localValues.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $localValues.additionalVolumes }}
      volumes:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
