name: Linter
on: pull_request
jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '16.x'

      - name: Run checks
        env:
          PER_PAGE: 100
          PR_URL: "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
          COUNT_CHANGED_FILES: $(curl -s -X GET -G $PR_URL | jq .changed_files)
          COUNT_PAGES: $((($COUNT_CHANGED_FILES / $PER_PAGE) + ($COUNT_CHANGED_FILES % $PER_PAGE > 0)))
        run: |
          for PAGE in $(seq 1 $COUNT_PAGES); do
            URL="$PR_URL/files?page=$PAGE&per_page=$PER_PAGE"
            PR_FILES=$(curl -s -X GET -G $URL | jq -r '.[] | select(.status != "removed") | .filename')
            for FILE in $PR_FILES; do
                EXTENSION="${FILE##*.}"
                if [[ $EXTENSION == 'js' || $EXTENSION == 'ts' || $EXTENSION == 'jsx' || $EXTENSION == 'tsx' ]]; then
                    CHANGED_FILES+=" $FILE"
                fi
            done
          done

          if [[ ! -z $CHANGED_FILES ]]; then
            npm ci
            cd tests && npm ci && cd ..
            npm install eslint-detailed-reporter --save-dev --legacy-peer-deps
            mkdir -p eslint_report

            echo "ESLint version: "`npx eslint --version`
            echo "The files will be checked: "`echo $CHANGED_FILES`
            npx eslint $CHANGED_FILES -f node_modules/eslint-detailed-reporter/lib/detailed.js -o ./eslint_report/eslint_checks.html
          else
            echo "No files with the \"js|ts|jsx|tsx\" extension found"
          fi

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: eslint_report
          path: eslint_report
