name: Pylint
on: pull_request
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: files
        uses: tj-actions/changed-files@v35.9.2
        with:
          files: |
              **/*.py

      - name: Run checks
        env:
          PR_FILES_AM: ${{ steps.files.outputs.added_modified }}
          PR_FILES_RENAMED: ${{ steps.files.outputs.renamed }}
        run: |
          CHANGED_FILES="${{steps.files.outputs.all_changed_files}}"

          if [[ ! -z $CHANGED_FILES ]]; then
            sudo apt-get --no-install-recommends install -y build-essential curl python3-dev python3-pip python3-venv
            python3 -m venv .env
            . .env/bin/activate
            pip install -U pip wheel setuptools
            pip install $(egrep "pylint.*==.*" ./cvat/requirements/development.txt)
            pip install $(egrep "django==.*" ./cvat/requirements/base.txt)

            echo "Pylint version: "$(pylint --version | head -1)
            echo "The files will be checked: "$(echo $CHANGED_FILES)
            pylint $CHANGED_FILES
            deactivate
          else
            echo "No files with the \"py\" extension found"
          fi
