name: Linter
on: pull_request
jobs:
  PyLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run checks
        env:
          PER_PAGE: 100
          PR_URL: "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
          COUNT_CHANGED_FILES: $(curl -s -X GET -G $PR_URL | jq .changed_files)
          COUNT_PAGES: $((($COUNT_CHANGED_FILES / $PER_PAGE) + ($COUNT_CHANGED_FILES % $PER_PAGE > 0)))
        run: |
          for PAGE in $(seq 1 $COUNT_PAGES); do
            URL="$PR_URL/files?page=$PAGE&per_page=$PER_PAGE"
            PR_FILES=$(curl -s -X GET -G $URL | jq -r '.[] | select(.status != "removed") | .filename')
            for FILE in $PR_FILES; do
                EXTENSION="${FILE##*.}"
                if [[ $EXTENSION == 'py' ]]; then
                    CHANGED_FILES+=" $FILE"
                fi
            done
          done

          if [[ ! -z $CHANGED_FILES ]]; then
            sudo apt-get --no-install-recommends install -y build-essential curl python3-dev python3-pip python3-venv
            python3 -m venv .env
            . .env/bin/activate
            pip install -U pip wheel setuptools
            pip install pylint-json2html
            pip install $(egrep "pylint.*" ./cvat/requirements/development.txt)
            pip install $(egrep "Django.*" ./cvat/requirements/base.txt)
            mkdir -p pylint_report

            echo "Pylint version: "`pylint --version | head -1`
            echo "The files will be checked: "$(echo $CHANGED_FILES)
            pylint $CHANGED_FILES --output-format=json > ./pylint_report/pylint_checks.json || EXIT_CODE=`echo $?` || true
            pylint-json2html -o ./pylint_report/pylint_checks.html ./pylint_report/pylint_checks.json
            deactivate
            exit $EXIT_CODE
          else
            echo "No files with the \"py\" extension found"
          fi

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: pylint_report
          path: pylint_report
